name: DeployLayer Lambda
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - apps/layer/**/*

defaults:
  run:
    working-directory: apps/layer/

jobs:
  deploy:
    name: 'DeployLayer Lambda'
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Configure AWS Credentials Action For GitHub Actions
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Give file permissions
        run: chmod 744 ./build.sh

      - name: Build
        run: ./build.sh

      - name: Push to S3
        run: aws s3api put-object --bucket nodejs-meetup-lambda-layers --key nodejs-meetup.zip --body layer_content.zip
